[project]
name = "30239-notes"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "altair>=5.4.1",
    "jupyter>=1.1.1",
    "marimo>=0.8.20",
    "pandas>=2.2.3",
    "polars>=1.8.2",
]
